accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    # profile
    path('<str:username>/', views.profile, name='profile'),
    # follow
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# 이미지
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('instargram/', include('instargram.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instargram/urls.py
from django.urls import path
from . import views
app_name = 'instargram'

urlpatterns = [
    path('', views.first, name='first'),   
    path('index', views.index, name='index'), 
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),

    # Like
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:pk>/detail_like/', views.detail_like, name='detail_like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

#Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField(
        'self',
        symmetrical=False,
        related_name='followers')

instargram/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Instargram(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, # 관계를 지어주는 모델명
        related_name='like_instargram', # User 모델을 위한 설정
    )

    def __str__(self):
        return self.title


class Comment(models.Model):
    instargram = models.ForeignKey(Instargram, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


class Like(models.Model):
    instargram = models.ForeignKey(Instargram, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields 

instargram/forms.py
from django import forms
from .models import Instargram, Comment


class InstargramForm(forms.ModelForm):

    class Meta:
        model = Instargram
        fields = ('title', 'content','image',)
        # exclude = ('title',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('instargram', 'user',)

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import (
    AuthenticationForm, 
    UserCreationForm, 
    PasswordChangeForm,
)
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth import get_user_model

# Create your views here.

def login(request):
    if request.user.is_authenticated:
        pass
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())
            #pass
            return redirect('instargram:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }    
    return render(request, 'accounts/login.html', context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('instargram:index')
    else:
        form = CustomUserChangeForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/signup.html', context)


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('accounts:login')


def profile(request,username):
    # 1. 현재 요청을 보낸 유저가 보고자하는 유저를 가져오기
    User = get_user_model() #User 모델 == 클래스
    profile_user = User.objects.get(username=username)
    
    context = {
        'profile_user' : profile_user,
    }
    return render(request, 'accounts/profile.html', context)    


def follow(request, user_pk):
    User = get_user_model() # User모델
    me = request.user # 팔로우 하는 사람
    counter = get_object_or_404(User, pk=user_pk)
    if request.user.is_authenticated:
        if me != counter: # 다를때
            # 상대방 목록에 내가 있는지
            if counter.followers.filter(pk=me.pk).exists():
                counter.followers.remove(me) # 팔로우취소
            else:
                counter.followers.add(me) # 팔로우
        # 상대방 프로필로 보냄
        return redirect('accounts:profile', counter.username) 
    return redirect('accounts:login')  # 로그인 안했으면

instargram/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Instargram, Comment
from .forms import InstargramForm, CommentForm

#Create your views here.
def first(request):
    if request.user.is_authenticated:
        return redirect('instargram:index')

    else:
        return redirect('accounts:login')

def index(request):
    instargram_list = Instargram.objects.order_by('-pk')
    context = {
        'instargram_list' : instargram_list,
    }
    return render(request,'instargram/index.html', context)


def create(request):
        if request.method == "POST":

            form = InstargramForm(request.POST, request.FILES)

            if form.is_valid():
                article = form.save(commit=False)
                article.user = request.user
                article.save()
                
                return redirect('instargram:detail', article.pk)
        else:
            form = InstargramForm()
        context = {
            'form':form,
        }    
        return render(request,'instargram/create.html',context)


def detail(request, pk):
    article = get_object_or_404(Instargram, pk=pk)
    context = {
        'article': article,
    }    
    return render(request,'instargram/detail.html', context)


def delete(request, pk):
    article = get_object_or_404(Instargram, pk=pk)
    if request.user.is_authenticated:
        if request.user == article.user:
            article.delete()
            return redirect('instargram:index')
    return redirect('instargram:detail', article.pk)    

def update(request, pk):
    article = get_object_or_404(Instargram, pk=pk)
    if request.user == article.user:
        if request.method == 'POST':

            form = InstargramForm(request.POST,request.FILES, instance=article)

            if form.is_valid():
                article = form.save()
                return redirect('instargram:detail', article.pk)
        else:
            form = InstargramForm(instance=article)
    else:
        return redirect('instargram:index')
        # return HttpResponseForbidden()
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'instargram/update.html', context)


def like(request, pk):
    instargram = get_object_or_404(Instargram, pk=pk)

    if instargram.like_users.filter(pk=request.user.pk).exists():
        instargram.like_users.remove(request.user)
    else:
        instargram.like_users.add(request.user)

    return redirect('instargram:index')


def detail_like(request, pk):
    instargram = get_object_or_404(Instargram, pk=pk)

    if instargram.like_users.filter(pk=request.user.pk).exists():
        instargram.like_users.remove(request.user)
    else:
        instargram.like_users.add(request.user)

    return redirect('instargram:detail', pk)
        

accounts/templates/accounts/login.html
{% extends 'first.html' %}

{% block content %}
<div class='container'>
  <form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success">Login</button>
  </form>
  
  <form action="{% url 'accounts:signup' %}" method="POST">
  {% csrf_token %}
  <button class="btn btn-primary">Signup</button>
  </form>

</div>

{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ profile_user }}님의 페이지</h2>
<div class='mx-5'>
<header class='d-flex'>
<div >
 <figure class="figure">
  <img src="..." class="figure-img img-fluid rounded" alt="...">
  <figcaption class="figure-caption">A caption for the above image.</figcaption>
</figure>
</div>
<section>
  <div class='d-flex' >
    <h2>{{ profile_user }}</h2>
    <div class='d-flex'>
      <div>
        <button>메세지 보내기</button>
      </div>
      <div>
        {% comment %} 팔로우 버튼 {% endcomment %}
        <form action="{% url 'accounts:follow' profile_user.pk %}" method="POST">
        {% csrf_token %}
          {% if request.user not in  profile_user.followers.all %}
            <button >팔로우</button>
          {% else %}
            <button >팔로우 취소</button>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
  {% comment %} 게시글, 팔로우, 팔로워 목록 {% endcomment %}
  <ul class='d-flex list-group list-group-horizontal' >
    <li class="list-group-item">게시물 {{ profile_user.instargram_set.all.count }}</li>
    <li class="list-group-item">팔로워 {{ profile_user.followers.all.count }}</li>
    <li class="list-group-item">팔로우 {{ profile_user.followings.all.count }}</li>
  </ul>
  
</section>
</header>


{% comment %} 글 {% endcomment %}
{% for article in profile_user.instargram_set.all %}

  <div class='container'>
  {{ article.title }}
  {{ article.content }}
  <p>
    {% if article.image %}
      <img src="{{ article.image.url }}" alt="{{ article.image }}">
    {% endif %}
  </p>


  </div>

{% endfor %}

  <div>
  <h5>게시글 작성</h5>
  <a href="{% url 'instargram:create' %}">[CREATE]</a>

  <a href="{% url 'instargram:index'  %}">[back]</a>

  </div>

</div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% comment %} {% extends 'base.html' %} {% endcomment %}

{% block content %}
<h1>회원가입</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

{% endblock  %}

config/templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>


{% block content %}
{% endblock  %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

config/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand fst-italic fw-bold" href="{% url 'instargram:index' %}">Instargram</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>


 
    <form class="d-flex">
      <input class="form-control" type="search" placeholder="검색" aria-label="Search">
      <button class="btn btn-outline-white" type="submit">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>
      </button>
    </form>
 


    <div  id="navbarSupportedContent">

      <ul class="navbar-nav">

        <li class="nav-item">
          <form action="{% url 'instargram:index' %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
            </svg>
          </button>
          </form>
        </li>

        <li class="nav-item">
          <form action="#" method="POST">
          {% csrf_token %}
          <button class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-chat-left-dots-fill" viewBox="0 0 16 16">
            <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm5 4a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg>
          </button>
          </form>
        </li>

        <li class="nav-item">
          <form action="#" method="POST">
          {% csrf_token %}
          <button class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-compass" viewBox="0 0 16 16">
              <path d="M8 16.016a7.5 7.5 0 0 0 1.962-14.74A1 1 0 0 0 9 0H7a1 1 0 0 0-.962 1.276A7.5 7.5 0 0 0 8 16.016zm6.5-7.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
              <path d="m6.94 7.44 4.95-2.83-2.83 4.95-4.949 2.83 2.828-4.95z"/>
            </svg>
          </button>
          </form>
        </li>
        
          <li class="nav-item">
          <form action="#" method="POST">
          {% csrf_token %}
          <button class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
              <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
            </svg>
          </button>
          </form>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
            </svg>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:profile' request.user.username %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
              <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
              </svg> 프로필</a>
            </li>
            
            <li><a class="dropdown-item" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmarks" viewBox="0 0 16 16">
              <path d="M2 4a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v11.5a.5.5 0 0 1-.777.416L7 13.101l-4.223 2.815A.5.5 0 0 1 2 15.5V4zm2-1a1 1 0 0 0-1 1v10.566l3.723-2.482a.5.5 0 0 1 .554 0L11 14.566V4a1 1 0 0 0-1-1H4z"/>
              <path d="M4.268 1H12a1 1 0 0 1 1 1v11.768l.223.148A.5.5 0 0 0 14 13.5V2a2 2 0 0 0-2-2H6a2 2 0 0 0-1.732 1z"/>
              </svg> 저장됨</a>
            </li>

            <li><a class="dropdown-item" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
              <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
              <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
              </svg> 설정</a>
            </li>

            <li><a class="dropdown-item" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16">
              <path d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z"/>
              <path fill-rule="evenodd" d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z"/>
              </svg> 계정전환</a>
            </li>
            
            <li><hr class="dropdown-divider"></li>
            <li><a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a></li>
        
          </ul>
        </li>
      </ul>

      
    </div>
  </div>
</nav>

instargram/templates/instargram/detail.html
{% extends 'base.html' %}
{% load humanize %}



{% block content %}
<div class='container'>
  <h2>Detail</h2>
  <h3>{{ article.pk }} 번째 글</h3>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>

  <p>
    {% if article.image %}
      <img src="{{ article.image.url }}" alt="{{ article.image }}">
    {% endif %}
  </p>
  <hr>

  <p>작성시각 : {{ article.created_at|naturalday }}</p>
  <p>수정시각 : {{ article.updated_at|naturaltime }}</p>
  <hr>
    {% if request.user == article.user %}
      <a href="{% url 'instargram:update' article.pk %}" class="btn btn-primary">[UPDATE]</a>
      <form action="{% url 'instargram:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">DELETE</button>
      </form>
    {% endif %}

    <form action="{% url 'instargram:detail_like' article.pk%}" method="POST">
      {% csrf_token %}
      {% if request.user in article.like_users.all %}
        <button class='btn btn-white'>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
          </svg>
        </button>
        {% else %}
        <button class='btn btn-white'>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
          </svg>
        </button>
        {% endif %}
     
    </form>
    <P>{{ article.like_users.count }} 명이 좋아합니다. </P>

    <a href="{% url 'instargram:index'  %}">[back]</a>
</div>

{% endblock  %}

instargram/templates/instargram/index.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>

  <h1>메인 페이지</h1>

  {% for article in instargram_list %} 
  {% comment %} 이 부분 변수명 article -> instargram으로 바꿔도 되나요 ? {% endcomment %}
  <p>
    <b>
      <a href="{% url 'accounts:profile' article.user.username %}">작성자:  {{ article.user }}</a>
    </b>
  </p>
    <p>글 번호 : {{ article.pk }}</p>
    <p>글 제목 : {{ article.title }}</p>
    <p>글 내용 : {{ article.content }}</p>

    <p>
      {% if article.image %}
        <img src="{{ article.image.url }}" alt="{{ article.image }}">
      {% endif %}
    </p>
    <form action="{% url 'instargram:like' article.pk %}" method="POST">
      {% csrf_token %}

    <hr>
        {% if request.user in article.like_users.all %}
        <button class='btn btn-white'>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
          </svg>
        </button>
        {% else %}
        <button class='btn btn-white'>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
          </svg>
        </button>
        {% endif %}
     
    </form>
    <P>{{ article.like_users.count }} 명이 좋아합니다. </P>

    <a href="{% url 'instargram:detail' article.pk %}">[DETAIL]</a>
    <hr>
  {% endfor %}

</div>
{% endblock  %}